local params = require("./params")
print(type(params["漫符"]))
print(type(params[1]))
print((params["漫符"]) == params.get("漫符"))
print((params[1]) == params.get(1))
print(params.get(1, 7))
print(params.get("漫符", 7))
print(params[1][7])
print(params["漫符"][7])

local options, name = params.get(1)
print(name, #options)
local options2, name2 = params.get("漫符")
print(name2 == name, options == options2)
