import * as commonUtils from './commonUtils';
import * as CustomUtils from './CustomUtils';
import * as MobxUtils from './MobxUtils';
import * as OptionsUtils from './OptionsUtils';
import * as ParseUtils from "./ParseUtils";
import { IPropertyUtils } from './PropertyUtils';
import TimeBufferUtils from './TimeBuffer';
import { typeFilterUtils, typeUtils } from "./TypeLib";
export declare type IUtils = typeof CustomUtils & typeof OptionsUtils & typeof typeUtils & typeof commonUtils & typeof TimeBufferUtils & IPropertyUtils & typeof typeFilterUtils & typeof ParseUtils & typeof MobxUtils;
export declare const Utils: IUtils;
