[package]
name = "core"
version = "0.1.0"
repository = "https://github.com/yuyiRai/yuyi-core"
authors = ["yuyiRai <yuyi919606952@foxmail.com>"]
# build = "src/main.rs"
edition = "2018"
license = "MIT/Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-test = "0.2"
uuid = { version = "0.7", default-features = false, features = ["v4", "wasm-bindgen"] }
digest = "0.8"
sha2 = "0.8"

[profile.release]
debug = false
lto = true
opt-level = 's'