"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var mobx_1 = require("mobx");
exports.observable = mobx_1.observable;
exports.observe = mobx_1.observe;
exports.computed = mobx_1.computed;
exports.action = mobx_1.action;
exports.intercept = mobx_1.intercept;
exports.obsSet = mobx_1.set;
exports.obsGet = mobx_1.get;
var mobx_react_1 = require("mobx-react");
exports.observer = mobx_react_1.observer;
