items:
  - name: SharePoint Framework reference
    href: ~/overview/sharepoint.md
    items:
      - name: utils
        uid: '@yuyi919/utils!'
        items:
          - name: AutoRunClass
            uid: '@yuyi919/utils!AutoRunClass:class'
          - name: DecoratorContextBase
            uid: '@yuyi919/utils!DecoratorContextBase:interface'
          - name: DeepPathUpdateOptions
            uid: '@yuyi919/utils!DeepPathUpdateOptions:interface'
          - name: EDateFormatter
            uid: '@yuyi919/utils!EDateFormatter:enum'
          - name: EventEmitter
            uid: '@yuyi919/utils!EventEmitter:class'
          - name: EventStore
            uid: '@yuyi919/utils!EventStore:class'
          - name: EventStoreProvider
            uid: '@yuyi919/utils!EventStoreProvider:class'
          - name: Expector
            uid: '@yuyi919/utils!Expector:interface'
          - name: FilterFunction (Namespace)
          - name: filterTo (Namespace)
          - name: HttpBox
            uid: '@yuyi919/utils!HttpBox:class'
          - name: ICommonFormContainer
            uid: '@yuyi919/utils!ICommonFormContainer:interface'
          - name: ICommonFormContainerTarget
            uid: '@yuyi919/utils!ICommonFormContainerTarget:interface'
          - name: IEscapeConvert
            uid: '@yuyi919/utils!IEscapeConvert:interface'
          - name: IEventStore
            uid: '@yuyi919/utils!IEventStore:interface'
          - name: IEventStoreBase
            uid: '@yuyi919/utils!IEventStoreBase:interface'
          - name: IGetPathResult
            uid: '@yuyi919/utils!IGetPathResult:interface'
          - name: IItemConfig
            uid: '@yuyi919/utils!IItemConfig:interface'
          - name: IMapTransformer
            uid: '@yuyi919/utils!IMapTransformer:interface'
          - name: isEqual (Namespace)
          - name: ITypeFilterUtils
            uid: '@yuyi919/utils!ITypeFilterUtils:interface'
          - name: ITypeUtils
            uid: '@yuyi919/utils!ITypeUtils:interface'
          - name: List (Class)
            uid: '@yuyi919/utils!List:class'
          - name: List (Namespace)
          - name: Observable$$
          - name: PathUpdateOptions
            uid: '@yuyi919/utils!PathUpdateOptions:interface'
          - name: PathUpdateResult
            uid: '@yuyi919/utils!PathUpdateResult:interface'
          - name: pipe (Namespace)
          - name: RecordMapStore
            uid: '@yuyi919/utils!RecordMapStore:class'
          - name: Setter
          - name: shiftKeyGroup (Namespace)
          - name: TrackMergeOptions
            uid: '@yuyi919/utils!TrackMergeOptions:interface'
          - name: Trasaction (Namespace)
          - name: TrasactionGenerator
            uid: '@yuyi919/utils!TrasactionGenerator:interface'
          - name: ValuePathIteratorOptions
            uid: '@yuyi919/utils!ValuePathIteratorOptions:interface'
      - name: CustomUtils
        uid: CustomUtils!
        items:
          - name: pipe (Namespace)
          - name: shiftKeyGroup (Namespace)
      - name: DateUtils
        uid: DateUtils!
        items:
          - name: EDateFormatter
            uid: 'DateUtils!EDateFormatter:enum'
      - name: DecoratorUtils
        uid: DecoratorUtils!
        items:
          - name: DecoratorContextBase
            uid: 'DecoratorUtils!DecoratorContextBase:interface'
          - name: Trasaction (Namespace)
          - name: TrasactionGenerator
            uid: 'DecoratorUtils!TrasactionGenerator:interface'
      - name: EventEmitter
        uid: EventEmitter!
        items:
          - name: EventEmitter
            uid: 'EventEmitter!EventEmitter:class'
          - name: Observable$$
      - name: LodashExtra
        uid: LodashExtra!
        items:
          - name: IEscapeConvert
            uid: 'LodashExtra!IEscapeConvert:interface'
          - name: isEqual (Namespace)
          - name: TrackMergeOptions
            uid: 'LodashExtra!TrackMergeOptions:interface'
      - name: MobxUtils
        uid: MobxUtils!
        items:
          - name: AutoRunClass
            uid: 'MobxUtils!AutoRunClass:class'
          - name: DeepPathUpdateOptions
            uid: 'MobxUtils!DeepPathUpdateOptions:interface'
          - name: EventStore
            uid: 'MobxUtils!EventStore:class'
          - name: EventStoreProvider
            uid: 'MobxUtils!EventStoreProvider:class'
          - name: IEventStore
            uid: 'MobxUtils!IEventStore:interface'
          - name: IEventStoreBase
            uid: 'MobxUtils!IEventStoreBase:interface'
          - name: IMapTransformer
            uid: 'MobxUtils!IMapTransformer:interface'
          - name: List (Class)
            uid: 'MobxUtils!List:class'
          - name: List (Namespace)
          - name: PathUpdateOptions
            uid: 'MobxUtils!PathUpdateOptions:interface'
          - name: PathUpdateResult
            uid: 'MobxUtils!PathUpdateResult:interface'
          - name: RecordMapStore
            uid: 'MobxUtils!RecordMapStore:class'
      - name: NodeUtils
        uid: NodeUtils!
        items:
          - name: Args
            uid: 'NodeUtils!Args:class'
          - name: ArgumentOptionsFixed
            uid: 'NodeUtils!ArgumentOptionsFixed:interface'
          - name: ArgumentParserFixed
            uid: 'NodeUtils!ArgumentParserFixed:interface'
      - name: OptionsUtils
        uid: OptionsUtils!
        items:
          - name: Setter
          - name: ValuePathIteratorOptions
            uid: 'OptionsUtils!ValuePathIteratorOptions:interface'
      - name: PropertyUtils
        uid: PropertyUtils!
        items:
          - name: IGetPathResult
            uid: 'PropertyUtils!IGetPathResult:interface'
      - name: TestUtils
        uid: TestUtils!
        items:
          - name: BenchmarkUtils
      - name: TsUtils
        uid: TsUtils!
        items:
          - name: Base
            uid: 'TsUtils!Base:class'
          - name: IFunction
            uid: 'TsUtils!IFunction:interface'
      - name: TypeLib
        uid: TypeLib!
        items:
          - name: Expector
            uid: 'TypeLib!Expector:interface'
          - name: FilterFunction (Namespace)
          - name: filterTo (Namespace)
          - name: ITypeFilterUtils
            uid: 'TypeLib!ITypeFilterUtils:interface'
          - name: ITypeUtils
            uid: 'TypeLib!ITypeUtils:interface'
      - name: WasmLoader
        uid: WasmLoader!
